In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm

In [2]:
from scipy.stats import  kstest

Загрузка чатей датасета (Основная часть и взаимодействия)

In [2]:
train = pd.read_csv('train.csv' , sep = ',') 
test = pd.read_csv('test.csv' , sep = ',')
train2w = pd.read_csv('two_way_inter_train_ED_check.csv' , sep = ',')
 
train3w = pd.read_csv('three_way_inter_train_ED_check.csv' , sep = ',')

FileNotFoundError: [Errno 2] No such file or directory: 'two_way_inter_train_ED_check.csv'

In [4]:
train.head()

,Property_ID,room,layout_type,property_type,locality,price,area,furnish_type,bathroom,city,...,floor,pet_friendly,power_backup,washing_machine,air_conditioner,geyser/solar,security_deposit,CCTV/security,lift,neighbourhood
0,42208,3,BHK,Independent House,Palavakkam,33624,1312,Furnished,2,Chennai,...,1,1,0,0,1,0,302616,0,0,300
1,90879,1,BHK,Apartment,Manikonda,9655,1474,Unfurnished,2,Hyderabad,...,17,0,1,0,0,1,19310,0,1,1600
2,99943,3,BHK,Apartment,Jodhpur Park,23699,1837,Semi-Furnished,2,Kolkata,...,10,1,1,1,1,0,118495,0,1,3100
3,113926,1,BHK,Apartment,Chembur,6306,606,Unfurnished,1,Mumbai,...,18,0,0,0,0,0,37836,0,1,300
4,185438,1,BHK,Studio Apartment,Kalewadi Pandhapur Road,12008,498,Semi-Furnished,3,Pune,...,14,0,0,1,1,0,72048,0,1,0

In [5]:
test.head()

,Property_ID,room,layout_type,property_type,locality,area,furnish_type,bathroom,city,parking_spaces,...,pet_friendly,power_backup,washing_machine,air_conditioner,geyser/solar,security_deposit,CCTV/security,lift,neighbourhood,price
0,114342,2,BHK,Independent Floor,Palava,1347,Semi-Furnished,1,Mumbai,0,...,0,1,1,1,0,72624,1,0,900,NaN
1,88819,1,BHK,Independent House,Somajiguda,634,Semi-Furnished,3,Hyderabad,1,...,0,0,1,1,0,19656,0,0,2500,NaN
2,85623,1,BHK,Apartment,Toli Chowki,524,Unfurnished,1,Hyderabad,1,...,1,1,0,0,0,7500,0,0,3200,NaN
3,130856,3,BHK,Apartment,Thane West,1837,Unfurnished,5,Mumbai,1,...,1,0,0,0,1,137646,1,1,1200,NaN
4,40089,2,BHK,Apartment,Krishnarajapura,1208,Semi-Furnished,2,Bangalore,1,...,0,1,1,1,0,110898,0,1,1000,NaN

In [65]:
train2w.head()

,room x layout_type,room x property_type,room x furnish_type,room x bathroom,room x city,room x parking_spaces,room x floor,room x power_backup,room x washing_machine,room x air_conditioner,...,power_backup x lift,washing_machine x geyser/solar,washing_machine x CCTV/security,washing_machine x lift,washing_machine x neighbourhood,air_conditioner x geyser/solar,air_conditioner x lift,air_conditioner x neighbourhood,geyser/solar x lift,CCTV/security x lift
0,3 x BHK,3 x Independent House,3 x Furnished,3 x 2,3 x Chennai,3 x 1,3 x 1,3 x 0,3 x 0,3 x 1,...,0 x 0,0 x 0,0 x 0,0 x 0,0 x 300,1 x 0,1 x 0,1 x 300,0 x 0,0 x 0
1,1 x BHK,1 x Apartment,1 x Unfurnished,1 x 2,1 x Hyderabad,1 x 0,1 x 17,1 x 1,1 x 0,1 x 0,...,1 x 1,0 x 1,0 x 0,0 x 1,0 x 1600,0 x 1,0 x 1,0 x 1600,1 x 1,0 x 1
2,3 x BHK,3 x Apartment,3 x Semi-Furnished,3 x 2,3 x Kolkata,3 x 0,3 x 10,3 x 1,3 x 1,3 x 1,...,1 x 1,1 x 0,1 x 0,1 x 1,1 x 3100,1 x 0,1 x 1,1 x 3100,0 x 1,0 x 1
3,1 x BHK,1 x Apartment,1 x Unfurnished,1 x 1,1 x Mumbai,1 x 0,1 x 18,1 x 0,1 x 0,1 x 0,...,0 x 1,0 x 0,0 x 0,0 x 1,0 x 300,0 x 0,0 x 1,0 x 300,0 x 1,0 x 1
4,1 x BHK,1 x Studio Apartment,1 x Semi-Furnished,1 x 3,1 x Pune,1 x 0,1 x 14,1 x 0,1 x 1,1 x 1,...,0 x 1,1 x 0,1 x 0,1 x 1,1 x 0,1 x 0,1 x 1,1 x 0,0 x 1,0 x 1

In [61]:
train3w.head()

,room x layout_type x furnish_type,room x layout_type x power_backup,room x layout_type x washing_machine,room x layout_type x air_conditioner,room x layout_type x lift,room x parking_spaces x pet_friendly,room x parking_spaces x washing_machine,room x power_backup x geyser/solar,room x washing_machine x lift,room x geyser/solar x lift,...,bathroom x power_backup x lift,bathroom x washing_machine x geyser/solar,bathroom x washing_machine x lift,bathroom x air_conditioner x CCTV/security,city x floor x air_conditioner,parking_spaces x washing_machine x lift,parking_spaces x air_conditioner x geyser/solar,parking_spaces x CCTV/security x neighbourhood,washing_machine x CCTV/security x lift,air_conditioner x CCTV/security x lift
0,3 x BHK x Furnished,3 x BHK x 0,3 x BHK x 0,3 x BHK x 1,3 x BHK x 0,3 x 1 x 1,3 x 1 x 0,3 x 0 x 0,3 x 0 x 0,3 x 0 x 0,...,2 x 0 x 0,2 x 0 x 0,2 x 0 x 0,2 x 1 x 0,Chennai x 1 x 1,1 x 0 x 0,1 x 1 x 0,1 x 0 x 300,0 x 0 x 0,1 x 0 x 0
1,1 x BHK x Unfurnished,1 x BHK x 1,1 x BHK x 0,1 x BHK x 0,1 x BHK x 1,1 x 0 x 0,1 x 0 x 0,1 x 1 x 1,1 x 0 x 1,1 x 1 x 1,...,2 x 1 x 1,2 x 0 x 1,2 x 0 x 1,2 x 0 x 0,Hyderabad x 17 x 0,0 x 0 x 1,0 x 0 x 1,0 x 0 x 1600,0 x 0 x 1,0 x 0 x 1
2,3 x BHK x Semi-Furnished,3 x BHK x 1,3 x BHK x 1,3 x BHK x 1,3 x BHK x 1,3 x 0 x 1,3 x 0 x 1,3 x 1 x 0,3 x 1 x 1,3 x 0 x 1,...,2 x 1 x 1,2 x 1 x 0,2 x 1 x 1,2 x 1 x 0,Kolkata x 10 x 1,0 x 1 x 1,0 x 1 x 0,0 x 0 x 3100,1 x 0 x 1,1 x 0 x 1
3,1 x BHK x Unfurnished,1 x BHK x 0,1 x BHK x 0,1 x BHK x 0,1 x BHK x 1,1 x 0 x 0,1 x 0 x 0,1 x 0 x 0,1 x 0 x 1,1 x 0 x 1,...,1 x 0 x 1,1 x 0 x 0,1 x 0 x 1,1 x 0 x 0,Mumbai x 18 x 0,0 x 0 x 1,0 x 0 x 0,0 x 0 x 300,0 x 0 x 1,0 x 0 x 1
4,1 x BHK x Semi-Furnished,1 x BHK x 0,1 x BHK x 1,1 x BHK x 1,1 x BHK x 1,1 x 0 x 0,1 x 0 x 1,1 x 0 x 0,1 x 1 x 1,1 x 0 x 1,...,3 x 0 x 1,3 x 1 x 0,3 x 1 x 1,3 x 1 x 0,Pune x 14 x 1,0 x 1 x 1,0 x 1 x 0,0 x 0 x 0,1 x 0 x 1,1 x 0 x 1

Исправление названий столбцов и значений в них. Приведение к одинаковому виду в TRAIN и TEST.

In [57]:
train2w.columns = [ I.replace('.x.' , ' x ') for I in train2w.columns ]
train2w.columns = [ I.replace('geyser solar' , 'geyser/solar') for I in train2w.columns ]
train2w.columns = [ I.replace('CCTV security' , 'CCTV/security') for I in train2w.columns ]

In [58]:
train3w.columns = [ I.replace('.x.' , ' x ') for I in train3w.columns ]
train3w.columns = [ I.replace('geyser.solar' , 'geyser/solar') for I in train3w.columns ]
train3w.columns = [ I.replace('CCTV.security' , 'CCTV/security') for I in train3w.columns ]

In [66]:
test2w = pd.DataFrame()
for i in tqdm( train2w.columns ) :
    
    coln = test[ i.split(' x ')].apply( lambda x: ' x '.join( str(u) for u in x), axis = 1)
    coln.name = i
    test2w = pd.concat([test2w , coln] , axis =1)

100%|██████████████████████████████████████████| 77/77 [01:00<00:00,  1.28it/s]

In [67]:
test3w = pd.DataFrame()
for i in tqdm( train3w.columns ) :
    
    coln = test[ i.split(' x ')].apply( lambda x: ' x '.join( str(u) for u in x), axis = 1)
    coln.name = i
    test3w = pd.concat([test3w , coln] , axis =1)

100%|██████████████████████████████████████████| 53/53 [00:39<00:00,  1.33it/s]

In [71]:
test2w.to_csv('two_way_inter_test.csv',sep = ',' , index = False)
test3w.to_csv('three_way_inter_test.csv',sep = ',' , index = False)

In [79]:
w4_cols = pd.read_csv('fourw_way_inter.csv' , sep = ',' , encoding='ISO-8859-1')

In [89]:
cols_4_train = pd.DataFrame()
cols_4_test = pd.DataFrame()

for I in tqdm( w4_cols['4_way_inter'].values ):
    print( I.replace('.','/').split(' è ') )
    tr = train[I.replace('.','/').split(' è ') ].apply( lambda x: ' x '.join( str(u) for u in x), axis = 1)
    tr.name = I.replace('.','/').replace(' è ',' x ')
    
    ts = test[ I.replace('.','/').split(' è ') ].apply( lambda x: ' x '.join( str(u) for u in x), axis = 1)
    ts.name = I.replace('.','/').replace(' è ',' x ')  
    
    stat , pv =  kstest(rvs = tr , 
                        cdf = ts )
    if pv < 0.05:
        print('Pval = ',pv  ,' Распределения неодинаковы')
    else:
        cols_4_train = pd.concat([ cols_4_train ,tr ] , axis=1)
        cols_4_test = pd.concat([ cols_4_test ,ts ] , axis=1)
        print('Pval = ',pv  ,' Распределения одинаковы')

  0%|                                                   | 0/28 [00:00<?, ?it/s]

['layout_type', 'property_type', 'parking_spaces', 'CCTV/security']

  4%|█▌                                         | 1/28 [00:03<01:21,  3.03s/it]

Pval =  0.26344463629408854  Распределения одинаковы
['layout_type', 'property_type', 'air_conditioner', 'CCTV/security']

  7%|███                                        | 2/28 [00:05<01:17,  2.99s/it]

Pval =  0.5410501373140022  Распределения одинаковы
['layout_type', 'furnish_type', 'city', 'geyser/solar']

 11%|████▌                                      | 3/28 [00:08<01:14,  2.96s/it]

Pval =  0.20090230039487245  Распределения одинаковы
['layout_type', 'furnish_type', 'power_backup', 'lift']

 14%|██████▏                                    | 4/28 [00:11<01:11,  2.99s/it]

Pval =  0.27314257406214215  Распределения одинаковы
['layout_type', 'furnish_type', 'CCTV/security', 'lift']

 18%|███████▋                                   | 5/28 [00:14<01:09,  3.00s/it]

Pval =  0.25629875807219893  Распределения одинаковы
['layout_type', 'city', 'parking_spaces', 'pet_friendly']

 21%|█████████▏                                 | 6/28 [00:17<01:05,  3.00s/it]

Pval =  0.49496199103055805  Распределения одинаковы
['layout_type', 'city', 'power_backup', 'geyser/solar']

 25%|██████████▊                                | 7/28 [00:20<01:03,  3.00s/it]

Pval =  0.35081966502375306  Распределения одинаковы
['layout_type', 'city', 'air_conditioner', 'geyser/solar']

 29%|████████████▎                              | 8/28 [00:24<01:00,  3.01s/it]

Pval =  0.3359249557678744  Распределения одинаковы
['layout_type', 'city', 'geyser/solar', 'lift']

 32%|█████████████▊                             | 9/28 [00:27<00:57,  3.01s/it]

Pval =  0.4696505109956316  Распределения одинаковы
['layout_type', 'parking_spaces', 'air_conditioner', 'lift']

 36%|███████████████                           | 10/28 [00:30<00:54,  3.05s/it]

Pval =  0.2577768906327057  Распределения одинаковы
['layout_type', 'parking_spaces', 'geyser/solar', 'CCTV/security']

 39%|████████████████▌                         | 11/28 [00:33<00:52,  3.07s/it]

Pval =  0.18128965302419087  Распределения одинаковы
['layout_type', 'power_backup', 'washing_machine', 'lift']

 43%|██████████████████                        | 12/28 [00:36<00:49,  3.11s/it]

Pval =  0.625762044629387  Распределения одинаковы
['layout_type', 'washing_machine', 'CCTV/security', 'lift']

 46%|███████████████████▌                      | 13/28 [00:39<00:47,  3.15s/it]

Pval =  0.5925140971482481  Распределения одинаковы
['layout_type', 'air_conditioner', 'geyser/solar', 'lift']

 50%|█████████████████████                     | 14/28 [00:42<00:43,  3.14s/it]

Pval =  0.1976928571899088  Распределения одинаковы
['layout_type', 'air_conditioner', 'CCTV/security', 'lift']

 54%|██████████████████████▌                   | 15/28 [00:45<00:40,  3.13s/it]

Pval =  0.7035022318647677  Распределения одинаковы
['property_type', 'parking_spaces', 'pet_friendly', 'washing_machine']

 57%|████████████████████████                  | 16/28 [00:49<00:37,  3.12s/it]

Pval =  0.893947996186824  Распределения одинаковы
['property_type', 'pet_friendly', 'washing_machine', 'geyser/solar']

 61%|█████████████████████████▍                | 17/28 [00:52<00:34,  3.12s/it]

Pval =  0.833907272398756  Распределения одинаковы
['furnish_type', 'city', 'parking_spaces', 'pet_friendly']

 64%|███████████████████████████               | 18/28 [00:55<00:31,  3.11s/it]

Pval =  0.7832093300070151  Распределения одинаковы
['furnish_type', 'city', 'parking_spaces', 'lift']

 68%|████████████████████████████▌             | 19/28 [00:58<00:28,  3.12s/it]

Pval =  0.8433025272075393  Распределения одинаковы
['furnish_type', 'city', 'power_backup', 'geyser/solar']

 71%|██████████████████████████████            | 20/28 [01:01<00:25,  3.15s/it]

Pval =  0.5549577784797324  Распределения одинаковы
['furnish_type', 'parking_spaces', 'CCTV/security', 'lift']

 75%|███████████████████████████████▌          | 21/28 [01:04<00:22,  3.16s/it]

Pval =  0.956655952826641  Распределения одинаковы
['city', 'parking_spaces', 'pet_friendly', 'air_conditioner']

 79%|█████████████████████████████████         | 22/28 [01:07<00:18,  3.15s/it]

Pval =  0.11222580466025045  Распределения одинаковы
['city', 'parking_spaces', 'washing_machine', 'lift']

 82%|██████████████████████████████████▌       | 23/28 [01:11<00:15,  3.16s/it]

Pval =  0.0807154319276423  Распределения одинаковы
['city', 'pet_friendly', 'air_conditioner', 'lift']

 86%|████████████████████████████████████      | 24/28 [01:14<00:12,  3.19s/it]

Pval =  0.15070196211760278  Распределения одинаковы
['city', 'washing_machine', 'geyser/solar', 'CCTV/security']

 89%|█████████████████████████████████████▌    | 25/28 [01:17<00:09,  3.12s/it]

Pval =  0.02192607224752876  Распределения неодинаковы
['city', 'air_conditioner', 'geyser/solar', 'CCTV/security']

 93%|███████████████████████████████████████   | 26/28 [01:20<00:06,  3.05s/it]

Pval =  0.04626712698194879  Распределения неодинаковы
['parking_spaces', 'pet_friendly', 'power_backup', 'geyser/solar']

 96%|████████████████████████████████████████▌ | 27/28 [01:23<00:03,  3.10s/it]

Pval =  0.8122550957946492  Распределения одинаковы
['parking_spaces', 'washing_machine', 'CCTV/security', 'lift']

100%|██████████████████████████████████████████| 28/28 [01:26<00:00,  3.10s/it]

Pval =  0.9871011461484622  Распределения одинаковы

In [91]:
cols_4_train

,layout_type x property_type x parking_spaces x CCTV/security,layout_type x property_type x air_conditioner x CCTV/security,layout_type x furnish_type x city x geyser/solar,layout_type x furnish_type x power_backup x lift,layout_type x furnish_type x CCTV/security x lift,layout_type x city x parking_spaces x pet_friendly,layout_type x city x power_backup x geyser/solar,layout_type x city x air_conditioner x geyser/solar,layout_type x city x geyser/solar x lift,layout_type x parking_spaces x air_conditioner x lift,...,property_type x pet_friendly x washing_machine x geyser/solar,furnish_type x city x parking_spaces x pet_friendly,furnish_type x city x parking_spaces x lift,furnish_type x city x power_backup x geyser/solar,furnish_type x parking_spaces x CCTV/security x lift,city x parking_spaces x pet_friendly x air_conditioner,city x parking_spaces x washing_machine x lift,city x pet_friendly x air_conditioner x lift,parking_spaces x pet_friendly x power_backup x geyser/solar,parking_spaces x washing_machine x CCTV/security x lift
0,BHK x Independent House x 1 x 0,BHK x Independent House x 1 x 0,BHK x Furnished x Chennai x 0,BHK x Furnished x 0 x 0,BHK x Furnished x 0 x 0,BHK x Chennai x 1 x 1,BHK x Chennai x 0 x 0,BHK x Chennai x 1 x 0,BHK x Chennai x 0 x 0,BHK x 1 x 1 x 0,...,Independent House x 1 x 0 x 0,Furnished x Chennai x 1 x 1,Furnished x Chennai x 1 x 0,Furnished x Chennai x 0 x 0,Furnished x 1 x 0 x 0,Chennai x 1 x 1 x 1,Chennai x 1 x 0 x 0,Chennai x 1 x 1 x 0,1 x 1 x 0 x 0,1 x 0 x 0 x 0
1,BHK x Apartment x 0 x 0,BHK x Apartment x 0 x 0,BHK x Unfurnished x Hyderabad x 1,BHK x Unfurnished x 1 x 1,BHK x Unfurnished x 0 x 1,BHK x Hyderabad x 0 x 0,BHK x Hyderabad x 1 x 1,BHK x Hyderabad x 0 x 1,BHK x Hyderabad x 1 x 1,BHK x 0 x 0 x 1,...,Apartment x 0 x 0 x 1,Unfurnished x Hyderabad x 0 x 0,Unfurnished x Hyderabad x 0 x 1,Unfurnished x Hyderabad x 1 x 1,Unfurnished x 0 x 0 x 1,Hyderabad x 0 x 0 x 0,Hyderabad x 0 x 0 x 1,Hyderabad x 0 x 0 x 1,0 x 0 x 1 x 1,0 x 0 x 0 x 1
2,BHK x Apartment x 0 x 0,BHK x Apartment x 1 x 0,BHK x Semi-Furnished x Kolkata x 0,BHK x Semi-Furnished x 1 x 1,BHK x Semi-Furnished x 0 x 1,BHK x Kolkata x 0 x 1,BHK x Kolkata x 1 x 0,BHK x Kolkata x 1 x 0,BHK x Kolkata x 0 x 1,BHK x 0 x 1 x 1,...,Apartment x 1 x 1 x 0,Semi-Furnished x Kolkata x 0 x 1,Semi-Furnished x Kolkata x 0 x 1,Semi-Furnished x Kolkata x 1 x 0,Semi-Furnished x 0 x 0 x 1,Kolkata x 0 x 1 x 1,Kolkata x 0 x 1 x 1,Kolkata x 1 x 1 x 1,0 x 1 x 1 x 0,0 x 1 x 0 x 1
3,BHK x Apartment x 0 x 0,BHK x Apartment x 0 x 0,BHK x Unfurnished x Mumbai x 0,BHK x Unfurnished x 0 x 1,BHK x Unfurnished x 0 x 1,BHK x Mumbai x 0 x 0,BHK x Mumbai x 0 x 0,BHK x Mumbai x 0 x 0,BHK x Mumbai x 0 x 1,BHK x 0 x 0 x 1,...,Apartment x 0 x 0 x 0,Unfurnished x Mumbai x 0 x 0,Unfurnished x Mumbai x 0 x 1,Unfurnished x Mumbai x 0 x 0,Unfurnished x 0 x 0 x 1,Mumbai x 0 x 0 x 0,Mumbai x 0 x 0 x 1,Mumbai x 0 x 0 x 1,0 x 0 x 0 x 0,0 x 0 x 0 x 1
4,BHK x Studio Apartment x 0 x 0,BHK x Studio Apartment x 1 x 0,BHK x Semi-Furnished x Pune x 0,BHK x Semi-Furnished x 0 x 1,BHK x Semi-Furnished x 0 x 1,BHK x Pune x 0 x 0,BHK x Pune x 0 x 0,BHK x Pune x 1 x 0,BHK x Pune x 0 x 1,BHK x 0 x 1 x 1,...,Studio Apartment x 0 x 1 x 0,Semi-Furnished x Pune x 0 x 0,Semi-Furnished x Pune x 0 x 1,Semi-Furnished x Pune x 0 x 0,Semi-Furnished x 0 x 0 x 1,Pune x 0 x 0 x 1,Pune x 0 x 1 x 1,Pune x 0 x 1 x 1,0 x 0 x 0 x 0,0 x 1 x 0 x 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134678,BHK x Independent Floor x 1 x 1,BHK x Independent Floor x 0 x 1,BHK x Unfurnished x Mumbai x 1,BHK x Unfurnished x 0 x 1,BHK x Unfurnished x 1 x 1,BHK x Mumbai x 1 x 1,BHK x Mumbai x 0 x 1,BHK x Mumbai x 0 x 1,BHK x Mumbai x 1 x 1,BHK x 1 x 0 x 1,...,Independent Floor x 1 x 0 x 1,Unfurnished x Mumbai x 1 x 1,Unfurnished x Mumbai x 1 x 1,Unfurnished x Mumbai x 0 x 1,Unfurnished x 1 x 1 x 1,Mumbai x 1 x 1 x 0,Mumbai x 1 x 0 x 1,Mumbai x 1 x 0 x 1,1 x 1 x 0 x 1,1 x 0 x 1 x 1
134679,BHK x Independent Floor x 0 x 0,BHK x Independent Floor x 0 x 0,BHK x Unfurnished x Pune x 1,BHK x Unfurnished x 1 x 0,BHK x Unfurnished x 0 x 0,BHK x Pune x 0 x 1,BHK x Pune x 1 x 1,BHK x Pune x 0 x 1,BHK x Pune x 1 x 0,BHK x 0 x 0 x 0,...,Independent Floor x 1 x 0 x 1,Unfurnished x Pune x 0 x 1,Unfurnished x Pune x 0 x 0,Unfurnished x Pune x 1 x 1,Unfurnished x 0 x 0 x 0,Pune x 0 x 1 x 0,Pune x 0 x 0 x 0,Pune x 1 x 0 x 0,0 x 1 x 1 x 1,0 x 0 x 0 x 0
134680,BHK x Apartment x 1 x 0,BHK x Apartment x 1 x 0,BHK x Semi-Furnished x Mumbai x 0,BHK x Semi-Furnished x 1 x 0,BHK x Semi-Furnished x 0 x 0,BHK x Mumbai x 1 x 0,BHK x Mumbai x 1 x 0,BHK x Mumbai x 1 x 0,BHK x Mumbai x 0 x 0,BHK x 1 x 1 x 0,...,Apartment x 0 x 1 x 0,Semi-Furnished x Mumbai x 1 x 0,Semi-Furnished x Mumbai x 1 x 0,Semi-Furnished x Mumbai x 1 x 0,Semi-Furnished x 1 x 0 x 0,Mumbai x 1 x 0 x 1,Mumbai x 1 x 1 x 0,Mumbai x 0 x 1 x 0,1 x 0 x 1 x 0,1 x 1 x 0 x 0
134681,BHK x Apartment x 0 x 0,BHK x Apartment x 0 x 0,BHK x Unfurnished x Pune x 0,BHK x Unfurnished x 1 x 1,BHK x Unfurnished x 0 x 1,BHK x Pune x 0 x 0,BHK x Pune x 1 x 0,BHK x Pune x 0 x 0,BHK x Pune x 0 x 1,BHK x 0 x 0 x 1,...,Apartment x 0 x 0 x 0,Unfurnished x Pune x 0 x 0,Unfurnished x Pune x 0 x 1,Unfurnished x Pune x 1 x 0,Unfurnished x 0 x 0 x 1,Pune x 0 x 0 x 0,Pune x 0 x 0 x 1,Pune x 0 x 0 x 1,0 x 0 x 1 x 0,0 x 0 x 0 x 1
134682,RK x Independent Floor x 0 x 0,RK x Independent Floor x 1 x 0,RK x Semi-Furnished x Chennai x 1,RK x Semi-Furnished x 0 x 1,RK x Semi-Furnished x 0 x 1,RK x Chennai x 0 x 0,RK x Chennai x 0 x 1,RK x Chennai x 1 x 1,RK x Chennai x 1 x 1,RK x 0 x 1 x 1,...,Independent Floor x 0 x 1 x 1,Semi-Furnished x Chennai x 0 x 0,Semi-Furnished x Chennai x 0 x 1,Semi-Furnished x Chennai x 0 x 1,Semi-Furnished x 0 x 0 x 1,Chennai x 0 x 0 x 1,Chennai x 0 x 1 x 1,Chennai x 0 x 1 x 1,0 x 0 x 0 x 1,0 x 1 x 0 x 1

In [92]:
cols_4_test

,layout_type x property_type x parking_spaces x CCTV/security,layout_type x property_type x air_conditioner x CCTV/security,layout_type x furnish_type x city x geyser/solar,layout_type x furnish_type x power_backup x lift,layout_type x furnish_type x CCTV/security x lift,layout_type x city x parking_spaces x pet_friendly,layout_type x city x power_backup x geyser/solar,layout_type x city x air_conditioner x geyser/solar,layout_type x city x geyser/solar x lift,layout_type x parking_spaces x air_conditioner x lift,...,property_type x pet_friendly x washing_machine x geyser/solar,furnish_type x city x parking_spaces x pet_friendly,furnish_type x city x parking_spaces x lift,furnish_type x city x power_backup x geyser/solar,furnish_type x parking_spaces x CCTV/security x lift,city x parking_spaces x pet_friendly x air_conditioner,city x parking_spaces x washing_machine x lift,city x pet_friendly x air_conditioner x lift,parking_spaces x pet_friendly x power_backup x geyser/solar,parking_spaces x washing_machine x CCTV/security x lift
0,BHK x Independent Floor x 0 x 1,BHK x Independent Floor x 1 x 1,BHK x Semi-Furnished x Mumbai x 0,BHK x Semi-Furnished x 1 x 0,BHK x Semi-Furnished x 1 x 0,BHK x Mumbai x 0 x 0,BHK x Mumbai x 1 x 0,BHK x Mumbai x 1 x 0,BHK x Mumbai x 0 x 0,BHK x 0 x 1 x 0,...,Independent Floor x 0 x 1 x 0,Semi-Furnished x Mumbai x 0 x 0,Semi-Furnished x Mumbai x 0 x 0,Semi-Furnished x Mumbai x 1 x 0,Semi-Furnished x 0 x 1 x 0,Mumbai x 0 x 0 x 1,Mumbai x 0 x 1 x 0,Mumbai x 0 x 1 x 0,0 x 0 x 1 x 0,0 x 1 x 1 x 0
1,BHK x Independent House x 1 x 0,BHK x Independent House x 1 x 0,BHK x Semi-Furnished x Hyderabad x 0,BHK x Semi-Furnished x 0 x 0,BHK x Semi-Furnished x 0 x 0,BHK x Hyderabad x 1 x 0,BHK x Hyderabad x 0 x 0,BHK x Hyderabad x 1 x 0,BHK x Hyderabad x 0 x 0,BHK x 1 x 1 x 0,...,Independent House x 0 x 1 x 0,Semi-Furnished x Hyderabad x 1 x 0,Semi-Furnished x Hyderabad x 1 x 0,Semi-Furnished x Hyderabad x 0 x 0,Semi-Furnished x 1 x 0 x 0,Hyderabad x 1 x 0 x 1,Hyderabad x 1 x 1 x 0,Hyderabad x 0 x 1 x 0,1 x 0 x 0 x 0,1 x 1 x 0 x 0
2,BHK x Apartment x 1 x 0,BHK x Apartment x 0 x 0,BHK x Unfurnished x Hyderabad x 0,BHK x Unfurnished x 1 x 0,BHK x Unfurnished x 0 x 0,BHK x Hyderabad x 1 x 1,BHK x Hyderabad x 1 x 0,BHK x Hyderabad x 0 x 0,BHK x Hyderabad x 0 x 0,BHK x 1 x 0 x 0,...,Apartment x 1 x 0 x 0,Unfurnished x Hyderabad x 1 x 1,Unfurnished x Hyderabad x 1 x 0,Unfurnished x Hyderabad x 1 x 0,Unfurnished x 1 x 0 x 0,Hyderabad x 1 x 1 x 0,Hyderabad x 1 x 0 x 0,Hyderabad x 1 x 0 x 0,1 x 1 x 1 x 0,1 x 0 x 0 x 0
3,BHK x Apartment x 1 x 1,BHK x Apartment x 0 x 1,BHK x Unfurnished x Mumbai x 1,BHK x Unfurnished x 0 x 1,BHK x Unfurnished x 1 x 1,BHK x Mumbai x 1 x 1,BHK x Mumbai x 0 x 1,BHK x Mumbai x 0 x 1,BHK x Mumbai x 1 x 1,BHK x 1 x 0 x 1,...,Apartment x 1 x 0 x 1,Unfurnished x Mumbai x 1 x 1,Unfurnished x Mumbai x 1 x 1,Unfurnished x Mumbai x 0 x 1,Unfurnished x 1 x 1 x 1,Mumbai x 1 x 1 x 0,Mumbai x 1 x 0 x 1,Mumbai x 1 x 0 x 1,1 x 1 x 0 x 1,1 x 0 x 1 x 1
4,BHK x Apartment x 1 x 0,BHK x Apartment x 1 x 0,BHK x Semi-Furnished x Bangalore x 0,BHK x Semi-Furnished x 1 x 1,BHK x Semi-Furnished x 0 x 1,BHK x Bangalore x 1 x 0,BHK x Bangalore x 1 x 0,BHK x Bangalore x 1 x 0,BHK x Bangalore x 0 x 1,BHK x 1 x 1 x 1,...,Apartment x 0 x 1 x 0,Semi-Furnished x Bangalore x 1 x 0,Semi-Furnished x Bangalore x 1 x 1,Semi-Furnished x Bangalore x 1 x 0,Semi-Furnished x 1 x 0 x 1,Bangalore x 1 x 0 x 1,Bangalore x 1 x 1 x 1,Bangalore x 0 x 1 x 1,1 x 0 x 1 x 0,1 x 1 x 0 x 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57717,BHK x Apartment x 1 x 0,BHK x Apartment x 1 x 0,BHK x Semi-Furnished x Mumbai x 0,BHK x Semi-Furnished x 0 x 0,BHK x Semi-Furnished x 0 x 0,BHK x Mumbai x 1 x 0,BHK x Mumbai x 0 x 0,BHK x Mumbai x 1 x 0,BHK x Mumbai x 0 x 0,BHK x 1 x 1 x 0,...,Apartment x 0 x 1 x 0,Semi-Furnished x Mumbai x 1 x 0,Semi-Furnished x Mumbai x 1 x 0,Semi-Furnished x Mumbai x 0 x 0,Semi-Furnished x 1 x 0 x 0,Mumbai x 1 x 0 x 1,Mumbai x 1 x 1 x 0,Mumbai x 0 x 1 x 0,1 x 0 x 0 x 0,1 x 1 x 0 x 0
57718,BHK x Apartment x 0 x 1,BHK x Apartment x 0 x 1,BHK x Unfurnished x Hyderabad x 0,BHK x Unfurnished x 0 x 0,BHK x Unfurnished x 1 x 0,BHK x Hyderabad x 0 x 1,BHK x Hyderabad x 0 x 0,BHK x Hyderabad x 0 x 0,BHK x Hyderabad x 0 x 0,BHK x 0 x 0 x 0,...,Apartment x 1 x 0 x 0,Unfurnished x Hyderabad x 0 x 1,Unfurnished x Hyderabad x 0 x 0,Unfurnished x Hyderabad x 0 x 0,Unfurnished x 0 x 1 x 0,Hyderabad x 0 x 1 x 0,Hyderabad x 0 x 0 x 0,Hyderabad x 1 x 0 x 0,0 x 1 x 0 x 0,0 x 0 x 1 x 0
57719,RK x Independent Floor x 1 x 1,RK x Independent Floor x 1 x 1,RK x Furnished x Ahmedabad x 1,RK x Furnished x 1 x 1,RK x Furnished x 1 x 1,RK x Ahmedabad x 1 x 1,RK x Ahmedabad x 1 x 1,RK x Ahmedabad x 1 x 1,RK x Ahmedabad x 1 x 1,RK x 1 x 1 x 1,...,Independent Floor x 1 x 0 x 1,Furnished x Ahmedabad x 1 x 1,Furnished x Ahmedabad x 1 x 1,Furnished x Ahmedabad x 1 x 1,Furnished x 1 x 1 x 1,Ahmedabad x 1 x 1 x 1,Ahmedabad x 1 x 0 x 1,Ahmedabad x 1 x 1 x 1,1 x 1 x 1 x 1,1 x 0 x 1 x 1
57720,BHK x Independent Floor x 0 x 0,BHK x Independent Floor x 0 x 0,BHK x Unfurnished x Delhi x 0,BHK x Unfurnished x 1 x 0,BHK x Unfurnished x 0 x 0,BHK x Delhi x 0 x 1,BHK x Delhi x 1 x 0,BHK x Delhi x 0 x 0,BHK x Delhi x 0 x 0,BHK x 0 x 0 x 0,...,Independent Floor x 1 x 0 x 0,Unfurnished x Delhi x 0 x 1,Unfurnished x Delhi x 0 x 0,Unfurnished x Delhi x 1 x 0,Unfurnished x 0 x 0 x 0,Delhi x 0 x 1 x 0,Delhi x 0 x 0 x 0,Delhi x 1 x 0 x 0,0 x 1 x 1 x 0,0 x 0 x 0 x 0
57721,BHK x Apartment x 0 x 1,BHK x Apartment x 1 x 1,BHK x Semi-Furnished x Delhi x 1,BHK x Semi-Furnished x 0 x 1,BHK x Semi-Furnished x 1 x 1,BHK x Delhi x 0 x 1,BHK x Delhi x 0 x 1,BHK x Delhi x 1 x 1,BHK x Delhi x 1 x 1,BHK x 0 x 1 x 1,...,Apartment x 1 x 1 x 1,Semi-Furnished x Delhi x 0 x 1,Semi-Furnished x Delhi x 0 x 1,Semi-Furnished x Delhi x 0 x 1,Semi-Furnished x 0 x 1 x 1,Delhi x 0 x 1 x 1,Delhi x 0 x 1 x 1,Delhi x 1 x 1 x 1,0 x 1 x 0 x 1,0 x 1 x 1 x 1

In [93]:
cols_4_train.to_csv('four_way_inter_train.csv',sep = ',' , index = False)
cols_4_test.to_csv('four_way_inter_test.csv',sep = ',' , index = False)